### PR TITLE
Allow batteries to charge items in trinket slots

### PR DESCRIPTION
**Pull request by jpenilla**
Tested and works, however, I haven't worked with the transfer API before so definitely possible I did it wrong.

### CODE REVIEW

**Review by Technici4n — COMMENTED** [review]
Did you check that this doesn't crash if trinkets is not loaded? That kind of loaded check is dangerous.

You can also use PlayerInventoryStorage.of(player) for the inventory.

Looks good otherwise

**Comment by jpenilla** [comment]
Imports don't exist in bytecode, so the class won't be loaded unless the if evaluates to true (and the synthetic methods generated by the lambdas only use Java/Minecraft types). Tested to make sure though, and no crashes when trinkets is missing.

**Comment by Technici4n** [comment]
Imports don't exist but lambdas can be problematic if they use parameters or capture variables from Trinkets. Just to be sure, you tried with a battery to make the class load, right?

**Comment by jpenilla** [comment]
Yes, tested with an enabled battery. Pushed another commit for insurance though. After that change, javap -p shows
```
Compiled from "FabricEnvHandler.java"
public class owmii.powah.fabric.FabricEnvHandler implements owmii.powah.EnvHandler {
  public owmii.powah.fabric.FabricEnvHandler();
  public void setupBlockItems();
  public void registerWorldgen();
  public void scheduleCommonSetup(java.lang.Runnable);
  public void handleReactorInitClient(java.util.function.Consumer<?>);
  public net.minecraft.tags.TagKey<net.minecraft.world.level.biome.Biome> getOverworldBiomeTag();
  public void registerTransfer();
  public owmii.powah.fabric.transfer.InventoryWrapper createInvWrapper(owmii.powah.lib.logistics.inventory.Inventory);
  public owmii.powah.fabric.transfer.TankWrapper createTankWrapper(owmii.powah.lib.logistics.fluid.Tank);
  public boolean interactWithTank(net.minecraft.world.entity.player.Player, net.minecraft.world.InteractionHand, owmii.powah.lib.logistics.fluid.Tank);
  public boolean canDischarge(net.minecraft.world.item.ItemStack);
  public boolean hasEnergy(net.minecraft.world.level.Level, net.minecraft.core.BlockPos, net.minecraft.core.Direction);
  public long pushEnergy(net.minecraft.world.level.Level, net.minecraft.core.BlockPos, net.minecraft.core.Direction, long);
  public owmii.powah.block.cable.CableTile createCable(net.minecraft.core.BlockPos, net.minecraft.world.level.block.state.BlockState, owmii.powah.block.Tier);
  public long chargeItemsInPlayerInv(net.minecraft.world.entity.player.Player, long, long, java.util.function.Predicate<net.minecraft.world.item.ItemStack>);
  public long chargeItemsInContainer(net.minecraft.world.Container, long, long);
  public long chargeItemsInContainer(net.minecraft.world.Container, long, long, java.util.function.Predicate<net.minecraft.world.item.ItemStack>);
  public long chargeItemsInInventory(owmii.powah.lib.logistics.inventory.Inventory, int, int, long, long);
  public long dischargeItemsInInventory(owmii.powah.lib.logistics.inventory.Inventory, long, long);
  private long transferSlotList(owmii.powah.fabric.FabricEnvHandler$EnergyTransferOperation, java.lang.Iterable<? extends net.fabricmc.fabric.api.transfer.v1.storage.base.SingleSlotStorage<net.fabricmc.fabric.api.transfer.v1.item.ItemVariant>>, long, long, java.util.function.Predicate<net.minecraft.world.item.ItemStack>);
  public java.lang.Object createTankWrapper(owmii.powah.lib.logistics.fluid.Tank);
  public java.lang.Object createInvWrapper(owmii.powah.lib.logistics.inventory.Inventory);
  private static boolean lambda$dischargeItemsInInventory$14(net.minecraft.world.item.ItemStack);
  private static boolean lambda$chargeItemsInInventory$13(net.minecraft.world.item.ItemStack);
  private static boolean lambda$chargeItemsInContainer$12(net.minecraft.world.item.ItemStack);
  private static void lambda$chargeItemsInPlayerInv$11(java.util.List, java.lang.String, java.util.Map);
  private static void lambda$chargeItemsInPlayerInv$10(java.util.List, java.lang.String, net.minecraft.world.Container);
  private static boolean lambda$interactWithTank$9(net.fabricmc.fabric.api.transfer.v1.fluid.FluidVariant);
  private static boolean lambda$interactWithTank$8(net.fabricmc.fabric.api.transfer.v1.fluid.FluidVariant);
  private static team.reborn.energy.api.EnergyStorage lambda$registerTransfer$7(net.minecraft.world.item.ItemStack, net.fabricmc.fabric.api.transfer.v1.context.ContainerItemContext);
  private static net.fabricmc.fabric.api.transfer.v1.storage.Storage lambda$registerTransfer$6(net.minecraft.world.level.Level, net.minecraft.core.BlockPos, net.minecraft.world.level.block.state.BlockState, net.minecraft.world.level.block.entity.BlockEntity, net.minecraft.core.Direction);
  private static net.fabricmc.fabric.api.transfer.v1.storage.Storage lambda$registerTransfer$5(net.minecraft.world.level.Level, net.minecraft.core.BlockPos, net.minecraft.world.level.block.state.BlockState, net.minecraft.world.level.block.entity.BlockEntity, net.minecraft.core.Direction);
  private team.reborn.energy.api.EnergyStorage lambda$registerTransfer$4(net.minecraft.world.level.Level, net.minecraft.core.BlockPos, net.minecraft.world.level.block.state.BlockState, net.minecraft.world.level.block.entity.BlockEntity, net.minecraft.core.Direction);
  private static boolean lambda$registerTransfer$3();
  private static net.fabricmc.fabric.api.transfer.v1.storage.Storage lambda$registerTransfer$2(net.minecraft.world.level.Level, net.minecraft.core.BlockPos, net.minecraft.world.level.block.state.BlockState, net.minecraft.world.level.block.entity.BlockEntity, net.minecraft.core.Direction);
  private static net.fabricmc.fabric.api.transfer.v1.storage.Storage lambda$registerTransfer$1(net.minecraft.world.level.Level, net.minecraft.core.BlockPos, net.minecraft.world.level.block.state.BlockState, net.minecraft.world.level.block.entity.BlockEntity, net.minecraft.core.Direction);
  private static team.reborn.energy.api.EnergyStorage lambda$registerTransfer$0(net.minecraft.world.level.Level, net.minecraft.core.BlockPos, net.minecraft.world.level.block.state.BlockState, net.minecraft.world.level.block.entity.BlockEntity, net.minecraft.core.Direction);
}
```

We can see
```
  private static void lambda$chargeItemsInPlayerInv$11(java.util.List, java.lang.String, java.util.Map);
  private static void lambda$chargeItemsInPlayerInv$10(java.util.List, java.lang.String, net.minecraft.world.Container);
```
are the new methods, which only reference mc and java in their signature.

**Comment by Technici4n** [comment]
Great, thank you for going the extra mile.

**Pull request merged**
